export const Curriculum_interface = {
  /* Datos personales */
  personal_data: {
    photo: null,
    first_secondname: null,
    second_secondname: null,
    name: null,
    typeid: null,
    id_number: null,
    sex: null,
    nacionality: null,
    country: null,
    military_card: {
      type: null,
      number: null,
      dm: null,
    },
    date_place_birth: {
      date: null,
      place: {
        country: null,
        depto: null,
        municipio: null,
      },
    },
    post_address: {
      address: null,
      country: null,
      depto: null,
      municipio: null,
      phone: null,
      email: null,
    },
  },
  /* Formacion academica */
  academic_training: {
    basic_half_education: {
      title: null,
      grade: null,
      dategrade: null,
    },
    high_education: [],
    lenguage: [],
  },
  /* Experiencia laboral */
  work_experience: [],
};

export const VModel_Curriculum_interface = [
  {
    property: "curriculumItem",
    oneKey: "editedCurriculum",
    defaultValue: { ...Curriculum_interface },
  },
  {
    property: "curriculumItemPersonalDataPhoto",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "photo",
    defaultValue: Curriculum_interface.personal_data.photo,
  },
  {
    property: "curriculumItemPersonalDataFirstSecondname",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "first_secondname",
    defaultValue: Curriculum_interface.personal_data.first_secondname,
  },
  {
    property: "curriculumItemPersonalDataSecondSecondname",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "second_secondname",
    defaultValue: Curriculum_interface.personal_data.second_secondname,
  },
  {
    property: "curriculumItemPersonalDataName",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "name",
    defaultValue: Curriculum_interface.personal_data.name,
  },
  {
    property: "curriculumItemPersonalDataTypeId",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "typeid",
    defaultValue: Curriculum_interface.personal_data.typeid,
  },
  {
    property: "curriculumItemPersonalDataIdNumber",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "id_number",
    defaultValue: Curriculum_interface.personal_data.id_number,
  },
  {
    property: "curriculumItemPersonalDataSex",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "sex",
    defaultValue: Curriculum_interface.personal_data.sex,
  },
  {
    property: "curriculumItemPersonalDataNacionality",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "nacionality",
    defaultValue: Curriculum_interface.personal_data.nacionality,
  },
  {
    property: "curriculumItemPersonalDataCountry",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "country",
    defaultValue: Curriculum_interface.personal_data.country,
  },
  {
    property: "curriculumItemPersonalDataMilitaryCardType",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "military_card",
    fourKey: "type",
    defaultValue: Curriculum_interface.personal_data.military_card.type,
  },
  {
    property: "curriculumItemPersonalDataMilitaryCardNumber",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "military_card",
    fourKey: "number",
    defaultValue: Curriculum_interface.personal_data.military_card.number,
  },
  {
    property: "curriculumItemPersonalDataMilitaryCardDM",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "military_card",
    fourKey: "dm",
    defaultValue: Curriculum_interface.personal_data.military_card.dm,
  },
  {
    property: "curriculumItemPersonalDataDatePlaceBirthDate",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "date_place_birth",
    fourKey: "date",
    defaultValue: Curriculum_interface.personal_data.date_place_birth.date,
  },
  {
    property: "curriculumItemPersonalDataDatePlaceBirthPlaceCountry",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "date_place_birth",
    fourKey: "place",
    fiveKey: "country",
    defaultValue:
      Curriculum_interface.personal_data.date_place_birth.place.country,
  },
  {
    property: "curriculumItemPersonalDataDatePlaceBirthPlaceDepto",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "date_place_birth",
    fourKey: "place",
    fiveKey: "depto",
    defaultValue:
      Curriculum_interface.personal_data.date_place_birth.place.depto,
  },
  {
    property: "curriculumItemPersonalDataDatePlaceBirthPlaceMunicipio",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "date_place_birth",
    fourKey: "place",
    fiveKey: "municipio",
    defaultValue:
      Curriculum_interface.personal_data.date_place_birth.place.municipio,
  },
  {
    property: "curriculumItemPersonalDataPostAddressAddress",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "address",
    defaultValue: Curriculum_interface.personal_data.post_address.address,
  },
  {
    property: "curriculumItemPersonalDataPostAddressCountry",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "country",
    defaultValue: Curriculum_interface.personal_data.post_address.country,
  },
  {
    property: "curriculumItemPersonalDataPostAddressDepto",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "depto",
    defaultValue: Curriculum_interface.personal_data.post_address.depto,
  },
  {
    property: "curriculumItemPersonalDataPostAddressMunicipio",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "municipio",
    defaultValue: Curriculum_interface.personal_data.post_address.municipio,
  },
  {
    property: "curriculumItemPersonalDataPostAddressPhone",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "phone",
    defaultValue: Curriculum_interface.personal_data.post_address.phone,
  },
  {
    property: "curriculumItemPersonalDataPostAddressEmail",
    oneKey: "editedCurriculum",
    twoKey: "personal_data",
    threeKey: "post_address",
    fourKey: "email",
    defaultValue: Curriculum_interface.personal_data.post_address.email,
  },
  /* Formacion academica */
  {
    property: "curriculumItemAcademicTrainingBasicHalfEducationTitle",
    oneKey: "editedCurriculum",
    twoKey: "academic_training",
    threeKey: "basic_half_education",
    fourKey: "title",
    defaultValue:
      Curriculum_interface.academic_training.basic_half_education.title,
  },
  {
    property: "curriculumItemAcademicTrainingBasicHalfEducationGrade",
    oneKey: "editedCurriculum",
    twoKey: "academic_training",
    threeKey: "basic_half_education",
    fourKey: "grade",
    defaultValue:
      Curriculum_interface.academic_training.basic_half_education.grade,
  },
  {
    property: "curriculumItemAcademicTrainingBasicHalfEducationDategrade",
    oneKey: "editedCurriculum",
    twoKey: "academic_training",
    threeKey: "basic_half_education",
    fourKey: "dategrade",
    defaultValue:
      Curriculum_interface.academic_training.basic_half_education.dategrade,
  },
  {
    property: "curriculumItemAcademicTrainingHighEducation",
    oneKey: "editedCurriculum",
    twoKey: "academic_training",
    threeKey: "high_education",
    defaultValue: Curriculum_interface.academic_training.high_education,
  },
  {
    property: "curriculumItemAcademicTrainingLenguage",
    oneKey: "editedCurriculum",
    twoKey: "academic_training",
    threeKey: "lenguage",
    defaultValue: Curriculum_interface.academic_training.lenguage,
  },
];
